spring:
  application:
    name: servicio-item
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}

#Para modificar el timeout de Hystrix y Ribbon, Hystrix envuelve a Ribbon, por lo que el timeout debe ser mayor.
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
#ribbon:
  #ConnectTimeout: 3000
  #ReadTimeout: 10000